server:
  port: 8090

spring:
  ai:
    openai:
      chat:
        options:
          model: gpt-3.5-turbo
        base-url: https://api.aigcapi.me
        api-key: sk-2TFAohVQGbmUtCyYB030D3237eA543878bC25b4cD817Ca1e
      api-key: sk-2TFAohVQGbmUtCyYB030D3237eA543878bC25b4cD817Ca1e
  mvc:
    async:
      request-timeout: -1

logging:
  file:
    name: .logs/chat-service.log
  level:
    root: info
    com.neusoft.neu24.chat.mapper: debug

nep:
  jwt:
    location: classpath:nep.jks
    alias: nanhu
    password: neu123456
    tokenTTL: 30m
